name: Build Camera HAL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip

    - name: Create HAL source
      run: |
        echo '#include <android/log.h>' > hal.cpp
        echo '' >> hal.cpp
        echo 'extern "C" {' >> hal.cpp
        echo 'void camera_hal_init() {' >> hal.cpp
        echo '    __android_log_write(3, "CameraHAL", "HAL loaded");' >> hal.cpp
        echo '}' >> hal.cpp
        echo '}' >> hal.cpp

    - name: Compile HAL
      run: |
        NDK="$GITHUB_WORKSPACE/android-ndk-r25b"
        $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang++ -shared -fPIC -o camera.msm8916.so hal.cpp -llog

    - name: Check result
      run: |
        if [ -f "camera.msm8916.so" ]; then
          echo "✅ HAL file created successfully!"
          ls -la camera.msm8916.so
        else
          echo "❌ Failed to create HAL file"
          exit 1
        fi

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: camera-hal
        path: camera.msm8916.so
