name: Test Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "test" > test.txt
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt
