name: Сборка Camera HAL для MSM8916

on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Загружаем исходный код
    - name: Загрузка кода
      uses: actions/checkout@v4
      
    # Шаг 2: Скачиваем и устанавливаем NDK вручную
    - name: Установка Android NDK
      run: |
        echo "Скачиваем Android NDK..."
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        echo "NDK установлен в $(pwd)/android-ndk-r25b"
        
    # Шаг 3: Компилируем для ARMv7
    - name: Компиляция Camera HAL
      run: |
        echo "=== ПРОВЕРКА ФАЙЛОВ ==="
        find . -name "*.cpp" -o -name "*.h" | head -15
        ls -la
        
        echo "=== НАСТРОЙКА ПЕРЕМЕННЫХ ==="
        export NDK_PATH=$GITHUB_WORKSPACE/android-ndk-r25b
        export TOOLCHAIN=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=armv7a-linux-androideabi
        export API=28
        
        echo "NDK Path: $NDK_PATH"
        echo "Toolchain: $TOOLCHAIN"
        
        echo "=== КОМПИЛЯЦИЯ ==="
        # Пробуем скомпилировать все CPP файлы
        $TOOLCHAIN/bin/$TARGET$API-clang++ \
          -shared -fPIC -std=c++17 \
          -o camera.msm8916.so \
          *.cpp \
          -I. \
          -llog -lutils -lcutils -lhardware \
          -DLOG_TAG=\"CameraHAL\" \
          -D__ARM_ARCH_7A__ \
          -Wno-multichar -Wno-deprecated-declarations -Wl,-soname,camera.msm8916.so
        
        echo "=== РЕЗУЛЬТАТ ==="
        if [ -f "camera.msm8916.so" ]; then
          echo "✅ УСПЕХ: Файл camera.msm8916.so создан!"
          file camera.msm8916.so
          ls -la camera.msm8916.so
        else
          echo "❌ ОШИБКА: Файл не создан"
          echo "Пробуем компилировать по одному файлу..."
          # Покажем какие .cpp файлы есть
          find . -name "*.cpp" -exec echo "Файл: {}" \;
        fi

    # Шаг 4: Сохраняем результат
    - name: Сохранение собранного файла
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: camera-msm8916-hal
        path: camera.msm8916.so
        retention-days: 30
        
    # Шаг 5: Отладочная информация если ошибка
    - name: Отладочная информация
      if: failure()
      run: |
        echo "=== ДЕТАЛИ ОШИБКИ ==="
        echo "Содержимое папки:"
        ls -la
        echo "CPP файлы:"
        find . -name "*.cpp"
        echo "H файлы:"
        find . -name "*.h"
