- name: Упрощенная компиляция
  if: failure()
  run: |
    export NDK_PATH=$GITHUB_WORKSPACE/android-ndk-r25b
    export TOOLCHAIN=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64
    
    # Создаем максимально простой HAL
    cat > simplest_hal.c << 'EOF'
    #include <android/log.h>
    
    #define LOG_TAG "SimpleHAL"
    
    __attribute__((visibility("default")))
    void dummy_function() {
        __android_log_write(ANDROID_LOG_INFO, LOG_TAG, "Minimal HAL loaded");
    }
    EOF
    
    $TOOLCHAIN/bin/armv7a-linux-androideabi28-clang \
      -shared -fPIC -o camera.msm8916.so \
      simplest_hal.c -llog
