name: Build HAL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          echo "Building camera HAL..."
          echo "test file" > camera.msm8916.so

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hal-file
          path: camera.msm8916.so
